--- #YAML:1.0
name:               NG
version:            0.001_02
abstract:           ~
author:
    - chenryn <rao.chenlin@gmail.com>
license:            Artistic_2_0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Deep:  0
    Test::More:  0
requires:
    AnyEvent::HTTP:       0
    autobox:              0
    autodie:              0
    Child:                0
    DBI:                  0
    File::Copy::Recursive:  0
    HTML::Element:        5.00
    HTML::Selector::XPath:  0
    HTML::TreeBuilder::XPath:  0
    perl:                 5.01
    Spreadsheet::ParseExcel:  0
    Spreadsheet::WriteExcel:  0
    SQL::Abstract:        0
    Time::HiRes:          0
    Try::Tiny:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
