---
abstract: unknown
author:
  - 'chenryn <rao.chenlin@gmail.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NG
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent::HTTP: 0
  Child: 0
  DBI: 0
  Digest::MD5: 0
  Email::MIME: 0
  File::Copy::Recursive: 0
  HTML::Element: 5.00
  HTML::Selector::XPath: 0
  HTML::TreeBuilder::XPath: 0
  JSON::XS: 0
  Net::SSH::Any: 0
  SQL::Abstract: 0
  Spreadsheet::ParseExcel: 0
  Spreadsheet::WriteExcel: 0
  Sys::CpuAffinity: 0
  Time::HiRes: 0
  Try::Tiny: 0
  XML::Simple: 0
  YAML::XS: 0
  autobox: 0
  autodie: 0
  perl: 5.01
version: 0.001_05
